# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Rite of Marriage"
  parent = "Start Here"
  url = "start-here/rite-of-marriage"
  weight = 20

[[main]]
  name = "Wedding Mass"
  parent = "Start Here"  
  url = "start-here/wedding-mass"
  weight = 20
  
[[main]]
  name = "Start Here"
  url = "start-here"
  weight = 20
 
[[main]]
  name = "FAQs"
  parent = "Start Here"
  url = "start-here/FAQs"
  weight = 20
 
 [[main]]
  name = "Glossary"
  parent = "Start Here"
  url = "start-here/glossary"
  weight = 20  
  
[[main]]
  name = "About this Site"
  parent = "Start Here"
  url = "start-here/about-this-site"
  weight = 20    
  
[[main]]
  name = "Wedding Planning"
  url = "wedding-planning"
  weight = 30  
  
[[main]]
  name = "Flowers"
  parent = "Wedding Planning"
  url = "wedding-planning/flowers"
  weight = 30

[[main]]
  name = "Marriage Preparation"
  parent = "Wedding Planning"
  url = "wedding-planning/marriage-preparation"
  weight = 30
  
 [[main]]
  name = "Music"
  parent = "Wedding Planning"
  url = "wedding-planning/music"
  weight = 30 
  
[[main]]
  name = "Programs"
  parent = "Wedding Planning"
  url = "wedding-planning/programs"
  weight = 30
  
[[main]]
  name = "Nuptial Blessing"
  parent = "Wedding Planning"
  url = "wedding-planning/nuptial-blessing"
  weight = 30   
  
[[main]]
  name = "Rubrics"
  parent = "Wedding Planning"
  url = "wedding-planning/rubrics"
  weight = 30
  
[[main]]
  name = "Rite of Betrothal"
  parent = "Wedding Planning"
  url = "wedding-planning/rite-of-betrothal"
  weight = 30
  
[[main]]
  name = "More Resources"
  url = "resources"
  weight = 40
  
[[main]]
  name = "About the Latin Mass"
  parent = "More Resources"
  url = "resources/about-the-latin-mass"
  weight = 40   
  
[[main]]
 name = "Mass Commentaries"
 parent = "More Resources"
 url = "resources/commentaries"
 weight = 40
  
[[main]]
  name = "History"
  parent = "More Resources"
  url = "resources/history"
  weight = 40 
  
[[main]]
  name = "Local Customs"
  parent = "More Resources"
  url = "resources/local-customs"
  weight = 40   

[[main]]
  name = "Walkthrough"
  parent = "More Resources"
  url = "resources/walkthrough"
  weight = 40  
  
[[main]]
  name = "Married Saints"
  parent = "More Resources"
  url = "resources/married-saints"
  weight = 40

[[main]]
  name = "Other Rites and Languages"
  parent = "More Resources"
  url = "resources/other-rites-and-languages"
  weight = 40   
  
[[main]]
  name = "Shop"
  parent = "More Resources"
  url = "resources/shop"
  weight = 40     

[[main]]
  name = "Pryares"
  parent = "More Resources"
  url = "resources/prayers"
  weight = 40   
  

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
