# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About"
  url = "about-2"
  weight = 10

[[main]]
  name = "Rite of Marriage"
  url = "rite-of-marriage"
  weight = 20

[[main]]
  name = "Wedding Mass"
  url = "the-wedding-mass"
  weight = 30
  
[[main]]
  name = "Start Here"
  url = "start-here"
  weight = 40
 
[[main]]
  name = "FAQs"
  parent = "Start Here"
  url = "start-here/FAQs"
  weight = 40
 
 [[main]]
  name = "Glossary"
  parent = "Start Here"
  url = "start-here/glossary"
  weight = 40  
  
[[main]]
  name = "About the Latin Mass"
  parent = "Start Here"
  url = "start-here/the-mass"
  weight = 40    
  
  
  
[[main]]
  name = "Wedding Planning"
  url = "wedding-planning"
  weight = 50  
  
[[main]]
  name = "Flowers"
  parent = "wedding-planning"
  url = "wedding-planning/flowers"
  weight = 50  

[[main]]
  name = "Marriage Preparation"
  parent = "Start Here"
  url = "start-here/marriage-preparation"
  weight = 40  
  
[[main]]
  name = "More Resources"
  url = "resources"
  weight = 60  
  
[[main]]
 name = "Mass Commentaries"
 parent = "More Resources"
 url = "resources/commentaries"
 weight = 60
  
[[main]]
  name = "History"
  parent = "More Resources"
  url = "resources/history"
  weight = 60  
  
  
  

  
[[main]]
  name = "Local Customs"
  parent = "Resources"
  url = "resources/local-customs"
  weight = 40    
  
[[main]]
  name = "Mass Music"
  parent = "Resources"
  url = "resources/mass-music"
  weight = 40  
  
[[main]]
  name = "Mass Programs"
  parent = "Resources"
  url = "resources/mass-programs"
  weight = 40  
  
[[main]]
  name = "Nuptial Blessing"
  parent = "Resources"
  url = "resources/nuptial-blessing"
  weight = 40    
  
[[main]]
  name = "Rubrics"
  parent = "Resources"
  url = "resources/rubrics-for-the-wedding-mass"
  weight = 40  
  
[[main]]
  name = "Walkthrough"
  parent = "Resources"
  url = "resources/walkthrough"
  weight = 40  
  
[[main]]
  name = "Married Saints"
  parent = "Resources"
  url = "resources/married-saints"
  weight = 40  
  
  [[main]]
  name = "Rite of Betrothal"
  parent = "Resources"
  url = "resources/rite-of-betrothal"
  weight = 40  
  
  [[main]]
  name = "Other Rites and Languages"
  parent = "Resources"
  url = "resources/other-rites-and-languages"
  weight = 40    
  
  [[main]]
  name = "Shop"
  parent = "Resources"
  url = "resources/shop"
  weight = 40      

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
