# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About"
  url = "about-2"
  weight = 10

[[main]]
  name = "Rite of Marriage"
  url = "rite-of-marriage"
  weight = 20

[[main]]
  name = "Wedding Mass"
  url = "the-wedding-mass"
  weight = 30

[[main]]
  name = "Resources"
  url = "resources"
  weight = 40
  
[[main]]
  name = Flowers
  parent = "Resources"
  url = "flowers"
  weight = 40

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
