---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: config/_default/content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: config/_default/content/The Rite of Marriage
  label: The rite of marriage
  create: all
  match: "**/*"
- type: directory
  path: config/_default/content/Home
  label: Home
  create: all
  match: "**/*"
- type: directory
  path: config/_default/content/The Wedding Mass
  label: The wedding mass
  create: all
  match: "**/*"
- type: directory
  path: config/_default/content/Other Resources
  label: Other resources
  create: all
  match: "**/*"
upload_dir: config/_default/static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.6
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.55.6
  preview_output_directory: public
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.55.6
