---
label: Text with media
hide_body: false
fields:
- name: text_heavy
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Text heavy
- name: media1
  type: file
  config:
    maxSize: 250
  label: media1
- name: gallery1
  type: image_gallery
  config: {}
  label: gallery1
- name: text_area
  type: text
  config:
    required: false
  label: text area
pages:
- config/_default/content/walkthrough.md
