---
label: Text heavy
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: title
- name: text
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: text
- name: toggle
  type: boolean
  label: toggle
pages:
- config/_default/content/Other Resources/other-resources.md
- config/_default/content/Other Resources/glossary.md
- config/_default/content/Other Resources/customs.md
- config/_default/content/Other Resources/faqs.md
- config/_default/content/Other Resources/commentaries.md
- config/_default/content/Home/home.md
- config/_default/content/texts.md
- config/_default/content/rubrics.md
- config/_default/content/the-rite-of-marriage.md
