---
label: Text heavy
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: title
- name: text
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: text
- name: toggle
  type: boolean
  label: toggle
pages:
- config/_default/content/texts.md
- config/_default/content/rubrics.md
- config/_default/content/faqs.md
- config/_default/content/other-resources.md
- config/_default/content/glossary-of-terms.md
