---
label: Text heavy
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: title
- name: text
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: text
- name: toggle
  type: boolean
  label: toggle
pages:
- content/Resources/married-saints.md
- content/about-2.md
