---
label: Title
hide_body: false
fields:
- name: name1
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Generic page
pages:
- config/_default/content/Home.md
